CREATE TABLE LOGIN
(
E_ID int references REGISTRATION(E_ID) PRIMARY KEY,
PASS varchar(20)
);
INSERT INTO LOGIN (E_ID,PASS) SELECT E_ID,PASS FROM REGISTRATION WHERE E_ID=1;
INSERT INTO LOGIN (E_ID,PASS) SELECT E_ID,PASS FROM REGISTRATION WHERE E_ID=2;
INSERT INTO LOGIN (E_ID,PASS) SELECT E_ID,PASS FROM REGISTRATION WHERE E_ID=3;
INSERT INTO LOGIN (E_ID,PASS) SELECT E_ID,PASS FROM REGISTRATION WHERE E_ID=4;
INSERT INTO LOGIN (E_ID,PASS) SELECT E_ID,PASS FROM REGISTRATION WHERE E_ID=5;
SELECT * FROM LOGIN;
