CREATE TABLE TRAIN_SERVICE
(
train_id int PRIMARY KEY,
train_name varchar(100)
);
INSERT INTO TRAIN_SERVICE VALUES('1337','SHATABDI DELHI');
INSERT INTO TRAIN_SERVICE VALUES('1338','SHATABDI KANPUR');
INSERT INTO TRAIN_SERVICE VALUES('1339','SHATABDI LUCKNOW');
INSERT INTO TRAIN_SERVICE VALUES('1340','SHATABDI PUNE');
SELECT * FROM TRAIN_SERVICE;
